[versions]
kotlin = "1.9.0"
jetbrainsKotlinJvm = "1.9.0"
rxjava = "2.2.21"
rxkotlin = "2.4.0"
gson = "2.10.1"

[libraries]
rxjava = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
rxkotlin = { group = "io.reactivex.rxjava2", name = "rxkotlin", version.ref = "rxkotlin" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

